nav:
  Home: /
  Writing: /blog/
  About: /about/

projects_url:

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo-circle.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: /
        twitter: /
        facebook: /
        linkedin: /
    show_all_posts: false
    post_count: 5
    highlight: monokai

# Rss
rss: ''

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-76776888-2 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
